### ISSUE TITLE
Issue with Steam and DCS.

### ISSUE THREAD

**Issue by Norziack** [JackD83/ALVR#102]
Hi, 

I have an issue and this happens with all the versions so far. I have a non official steam game, which launched perfectly in v2.4.0-alpha5 via Steam VR. However when i installed v8, it launched the game but it went back into Steam Home before it even came to the title screen. Im not sure what caused this.

**Comment by Norziack** [comment]
It seems DCS doesnt detect that theres a VR headset at all, since it actually starts in fullscreen while when i start it in 2.4 it goes into VR mode. Dont know if thats much help.

**Comment by JackD83** [comment]
DCS has a faulty detection of the headset. There is a workaround in faking a vive, but then the view is warped from bug #88. There is no solution yet

**Comment by Norziack** [comment]
I see, im really interested in getting my hands on your visual upgrades, like the correct resolution for the Quest. Is there any way to apply those improvements to polygraphene's latest build (v2.4) ? Because that works fine atm.

**Comment by zarik5** [comment]
I wanted to try to fix the warped view issue but I was unable to make DCS work in VR. I disabled the controllers through ALVR, connected a gamepad, launched the game through steam in SteamVR mode but on the headset (Oculus Quest) I only see the steamvr void. On the monitor the game is full screen in VR mode but does not respond to head movements and I cannot move the cursor.
What is the workaround?

**Comment by JackD83** [comment]
Its only the tracking system name that prevents DCS to detect VR: https://github.com/JackD83/ALVR/issues/31#issuecomment-530336209

**Comment by zarik5** [comment]
I found the fix first build! :) In OvrDisplayComponent::GetProjectionRaw i swapped eyeFov.bottom/eyeFov.top and there is no more warping! A similar thing happened to me while I was writing the FFR shaders, so that type of warping was familiar to me. The problem didn't appear before because the Oculus Quest used to return Oculus Go's 45deg for both fov top and fov bottom. Unfortunately there is no way to tell which game does this mistake, so I'm going to add a fix button similar to the Boneworks one.

**Comment by JackD83** [comment]
Man, you make me look bad :) I looked at the same code but was under the impression its left/right that was wrong and could not figure it out
