### ISSUE TITLE
No Audio at all on Oculus Quest

### ISSUE THREAD

**Issue by JashanChittesh** [JackD83/ALVR#103]
Audio works on the Quest, it also works via Link, or on the Vive (via SteamVR). However, with ALVR, I don't get any audio on the Quest at all. ALVR Server Sound has Steam Sound and Use default device "(Default) Headphones (Oculus Virtual Audio Device)" active. I tried it with both, Auto in the SteamVR settings, and manually selecting the Headphones (Oculus Virtual Audio Device) driver.

Quest audio is max, SteamVR audio (i.e. desktop audio) is also max. And yet, I don't hear anything (neither in my game, nor in the SteamVR dashboard).

Any ideas what I can do about this? Or how to troubleshoot?

Version is ALVR v2.4.0-experimental v8; downloaded about an hour ago from Releases.

**Comment by ghandye** [comment]
New ALVR user, but same problem here. Unable to get sound working through ALVR stream via any known combination of settings I've tried. My workaround for now is to play sound directly from PC to speakers and only use ALVR to stream video, but that causes audio/video sync issues.

**Comment by Rumik** [comment]
Same here - cannot get sound working. In the server's sound tab, what options should we be using?

**Comment by Rumik** [comment]
Got it working after messing around for a bit, changing which device was being used and restarting the app each time.

**Comment by JackD83** [comment]
Please provide some more info about your PCs. Like CPU, Mainboard and audio devices. 

You need a real and working audio device where the audio is captured back from. Virtual devices do not work. Make sure to update all drivers for all devices. Realtek audio drivers are known to produce errors.

**Comment by DavisNT** [comment]
Alternatively you can try to set audio output to a different device (e.g. install https://www.vb-audio.com/Cable/ ) to check whether the issue is device specific?

**Comment by Hansaplast** [comment]
Same here - no Audio with Experiment 9, video works very well though (smoother that alpha-5).
Audio and Video worked with alpha-5 from Polygraphene.

Just thought I'd post this info, incase it is helpful.

Hardware:
i7-6700HQ @ 2.6Ghz, nVidia GTX 1660 6gb mobile, laptop Razer Blade 14" MY 0216, 16Gb RAM.

Audio devices I can choose from:
- Oculus Audio (virtual), which will probably not work, since it may require the Link cable
- Realtek HD (reported problematic?)
- Razer Surround Audio Controller (I suspect this is a virtual audio device as well)

Software:
Windows 10 (10.0.18363.720).
The Quest is at V14, so is the Oculus desktop app.
nVidia drivers version 441.41 (the Quest Link wouldn't work with one of the most recent versions).
Latest Steam release version (not a beta).

Hope this is helpful.
Keep up the good work 😊

**Comment by JackD83** [comment]
Now we are getting somewhere. Are you both using Oculus Link and have installed the Oculus software? Oculus is messing with the default audio devices in Steam VR. Use [Advanced Settings](https://github.com/matzman666/OpenVR-AdvancedSettings/releases) to change the SteamVR Audio device to the same as in ALVR, in your case try the Realtek HD.

I don't know if the audio device can be set in the SteamVR UI directly

**Comment by Hansaplast** [comment]
I'v tried all possible combinations in SteamVR and the ALVR desktop app that I could come up with. Even reinstalled and updated the Audio Drivers. To no avail.

After that I've installed "Advanced Settings", and did all the tests again: still no sound.

Having said that, the entire setup (mostly in SteamVR) is a little confusing to me.
What would the ideal settings be for ALVR (desktop) and what settings for SteamVR.

With all these tests Oculus Desktop was not running. 
I have just been wandering in the SteamVR "home".

Also note, the settings in SteamVR options were:
Audio Output Device: Headset vs Manual
-> manual listed all the previously listed audio devices (none of them did anything)
Audio Mirroring: Headset vs Manual
-> manual again listing the previous listed audio devices.

In ALVR "Steam sound" is enabled. I've tried "Use Default device" and I've tried all 3 audio devices.

Note: With some combinations I do get audio from the PC, but nothing in the headset.

**Comment by Hansaplast** [comment]
Alright, getting a little closer: I now have menu sounds in SteamVR and in Half Life Alyx.
However: no sounds effects in the game itself (except when operating the menu).

ALVR: Steam sound checked (is this a typo? Stream sound? Or is it referring to Steam?). "Use defaukt device checked (combobox is showing "Realtek").

SteamVR: Audio Output set to manual (Realtek), Audio mirroring manual as well (Oculus Quest).

Oculus Desktop is not running during this test.

**Comment by JackD83** [comment]
> However: no sounds effects in the game itself (except when operating the menu).

That is not how it works. You either have sound from the application or not. If you really have this kind of issue, your system is messed up in some way.

Here are my sound settings. I only have to set it this way since I installed the oculus software. Before that the defaults worked fine.

![alvr](https://user-images.githubusercontent.com/15889805/77756850-5250f580-7030-11ea-9b57-f13145bd8e74.png)

![steamvr](https://user-images.githubusercontent.com/15889805/77756912-744a7800-7030-11ea-80ed-ae8c8be9f4a1.png)

The SteamVR audio settings are only visible if the headset is connected

**Comment by Hansaplast** [comment]
OK, matched your settings AND had Oculus Desktop running in the background: **Sounds now works.**

As for sound menu vs game effects: I get what you're saying. There either is sound, or there is no sound at all. But strangely enough: this is what happened. Don't know what to tell you. 

I'm thinking of doing a complete fresh install from the ground up (Windows included).
Thanks JackD83 - and thanks for a cool app.

**Comment by DavisNT** [comment]
@Hansaplast For me https://github.com/JackD83/ALVR/issues/142 also caused some very weird audio issues (sometimes when SteamVR launched either there was no sound at all or there was no sound from Steam VR home, but there was sound from Google Earth - I don't remember the details).

**Comment by Hansaplast** [comment]
Thanks DavisNT!
ALVR (exp. v9) has been running very well for me since I followed JackD83's suggestion. (thanks again JackD83!)

**Comment by orangpelupa** [comment]
anyone still got this no audio issue?

I used to be able to use ALVR alongside Link just fine (but have "no audio" warning on Link despite everything works fine). 

But then oculus fixed their link (oculus desktop app shows green, no more "no audio" warning) and i no longer can hear audio via ALVR.

**Comment by DavisNT** [comment]
@orangpelupa Probably you need to specify the same audio device in SteamVR settings and ALVR settings. 
See: https://github.com/JackD83/ALVR/issues/103#issuecomment-604980089

**Comment by orangpelupa** [comment]
@DavisNT yeah i already put the same audio device on them :(

thanks for informing me that v10 have audio settings fixed, maybe this fix result in unforseen bug, i will test by gradually going older and older version of ALVR

**Comment by orangpelupa** [comment]
solved. You need to 

1. Set windows default audio to "Audio A"
2. Set SteamVR to "Audio A"
3. Set ALVR to "Audio A"

replace "audio a" with whatever audio device you use. So if you didnt do step 1, yes ALVR/SteamVR will automatically change windows audio output to your desired audio device, but no sound will be heard on quest.

by doing step 1, it seems nothing different with not doing step 1. But turns out it fixed the audio.
