### ISSUE TITLE
ALVR + SteamVR + PCARS2 on RTX2070S

### ISSUE THREAD

**Issue by walterklomp** [JackD83/ALVR#107]
Hi,

Does anybody have some settings I can set to make the picture clearer especially distance? It seems everything more than 50m before the car is blur...  increasing the ALVR resolution to 125% helps a bit. I have SteamVR SS set to 100% (1440x1600 per eye), but when I set it to automatic, the GPU can’t keep up, which is odd as it’s a pretty powerful one.
It also seems that SS in PCARS2 doesn’t seem to have any effect but MSAA does (helps with artifacts, but not the blur vision)

Hope to find some tips and tricks.

Using Oculus link gets me nowhere... stuttering like crazy, unless I tone everything down, which makes it not nice.

**Comment by SSSTREDDD** [comment]
what is your cpu and ram?

**Comment by walterklomp** [comment]
3600x and 16Gb ram.  Meanwhile I have set SteamVR manually to 140% which matches ALVR 125% and in game supersampling to 1.0. Picture is now somewhat better, but still blur, especially in distance.

**Comment by TashaSkyUp** [comment]
In my experience the resolution setting in steamVR doesnt effect anything when ALVR is running things. And if the game doesn't work well in link.. Maybe get it working well in link first? do any of your titles work well with link?

**Comment by JackD83** [comment]
> In my experience the resolution setting in steamVR doesnt effect anything when ALVR is running things.

That's not the case. Reduce it to super sampling 0.5 and you will seed the difference. You can use  ALVR 125%, but that is only the video resolution transmitted to the Quest. In my opinion, it has hardly any impact on visual quality. 

@walterklomp Have you ever tried PCARS2 on another headset? I played with the Vive Pro and a Pimax 5k+ and both have blurry distance. PCARS2 is very demanding on higher resolutions

**Comment by walterklomp** [comment]
I’m now running with link again and Nvidia inspector... also latest update of oculus allows me to disable some layering function for which I don’t see any effect.  Just as blur but a little clearer.  I’ll still use ALVR for pavlov etc, because of no wires! :)

**Comment by T3ER** [comment]
> > In my experience the resolution setting in steamVR doesnt effect anything when ALVR is running things.
> 
> That's not the case. Reduce it to super sampling 0.5 and you will see the difference. You can use ALVR 125%, but that is only the video resolution transmitted to the Quest. In my opinion, it has hardly any impact on visual quality.
> 
> @walterklomp Have you ever tried PCARS2 on another headset? I played with the Vive Pro and a Pimax 5k+ and both have blurry distance. PCARS2 is very demanding on higher resolutions

Huh, it's a shame if you really can't supersample. I recall supersampling with success a few months ago. Something definitely happens when higher than 1.0 but the visual difference is practically none, it actually kinda blurs out the image and nothing changes afterwards. Gpu usage still rises, too. Lower values than 1 are clearly working in games that use the setting. Steamvr ui can't be supersampled at all. Having just 1,06 would make text much better to read.

**Comment by T3ER** [comment]
Well, nevermind, I've tested v8, v7 and v3. Can't really tell if there is or used to be difference since I don't have anything to compare against from a while ago. That is unless steamvr really did affect the supersampling somehow or the effect of supersampling was more noticeable in v1 with the bad image quality. I did try some other settings and couldn't change motion smoothing, at least it wouldn't work on vrchat. Forcing on had no effect on framerate. I did restart game and even steamvr.

**Comment by ScrambledGamingYT** [comment]
You could try Nvidia's new vr SS feature maybe that will help

**Comment by walterklomp** [comment]
Thanks!  I managed to finally get a smooth operation using Project Cars 2 on oculus link and also on Alvr... if your card supports VRSS, switch it on... it saves a ton of overhead and my frame rate shot up. Also using the Nvidia profile inspector tips on LOD and Clamping for distance sharpness helps instead of the in-app patch for sharpness which takes quite a bit of overhead and FPS. Having in app and steam-vr SS on 1 and letting either oculus link (1.3) or alvr (1.25) do the supersampling. Works like a charm. MSAA = low.
