### ISSUE TITLE
Need for detailed wireless settings.

### ISSUE THREAD

**Issue by TashaSkyUp** [JackD83/ALVR#108]
We need a detailed list of reccomended wireless settings besides 5ghz only/different ssid's and 40mhz channel width.

Please provide detailed settings for commonly available properties.

for instance for channel width i can choose 20mhz or AUTO, there is no 40mhz.
fat channel intolerant?
Mixed mode protection?
packet coalescing?
roaming agressivness?
throughput booster?

etc.

![image](https://user-images.githubusercontent.com/15312630/73138150-8490a780-402d-11ea-8b3d-ff77be458178.png)
![image](https://user-images.githubusercontent.com/15312630/73138204-14ceec80-402e-11ea-8f05-e5beb6a47d0b.png)

**Comment by Pesoen** [comment]
one thing i have found is that too high a channel will cause the quest to loose connection.. my current channel of 112 is perfect and has yet to suddenly loose connection. but above 130 it looses connection a ton.

as for specific settings, i don't now besides using an AP instead of a wifi card(usb of pcie), as the AP is easier to configure, depending on your existing network of course. i for instance use an RT-N66U for my networking, and it takes care of the wireless signal upstairs(where i game and sleep) and i use my modem for downstairs.
