### ISSUE TITLE
Controller seems to work at half the framerate

### ISSUE THREAD

**Issue by TheWors3** [JackD83/ALVR#184]
While the fps in both client and server is 72 fps when moving the controllers fast it seems fine but moving them slowly there is what it would seem like they are moving at a slower framerate, probably half. fps is 72 checked in steamvr constantly and hmd movement works fine. Also the desktop view shows nothing like this, only in hmd.

**Comment by zarik5** [comment]
I never experienced it, maybe you mean that the controllers lag behind? In that case you need to decrease "Pose time offset" in Other tab.

**Comment by TheWors3** [comment]
Yeah, i've already changed it to 0 and the delay is fine. I was referring to the percieved controller fps when moving them, it seems to have improved using a larger buffer but its nothing perfect. its like a jerky movement or judder

**Comment by JackD83** [comment]
Those stuttering occurs mostly if your PC is running at its limits and is probably caused by by the asynchronicity of tracking and rendering/encoding. For the headset, this is mitigated by the asynchronous timewarp of the Oculus runtime.

The same thing happens on the Oculus Link and is very perceivable in bad optimized games like Fallout 4 VR

**Comment by TheWors3** [comment]
i'm running a 2700x with a 1080ti and fps reported is 72, happens in every game including steamvr, both gpu and cpu not even reaching 80% usage. I'll try it on a gaming laptop and see if it still ocurrs

**Comment by orangpelupa** [comment]
maybe related to random judder bug for the whole vr experience in the headset? try running ALVR without any foveated rendering. In my case, it almost fixed the judder.
