### ISSUE TITLE
Linux PC side support?

### ISSUE THREAD

**Issue by poVoq** [JackD83/ALVR#23]
Assuming this uses the Nvidia SDK, than a Linux port should be feasible:
https://www.phoronix.com/scan.php?page=news_item&px=Video-Codec-SDK-9.0-Stable

SteamVR is supported under Linux and with Proton a surprising number of games can be made to run.

I realize that this is a tiny niche target, but with a high percentage of programmers that might be interested in contributing :)

**Comment by JackD83** [comment]
ALVR is Build around DX11, cuda and some windows sound APIs. Unless someone really dedicated will come around, alvr will stay a windows only software

**Comment by andy-d1969** [comment]
Someone should ask in the VKx Discord channel: https://discordapp.com/invite/b29gDTn
That's where all SteamPlay / Proton / DXVK devs meet.
Since Google uses Linux for their Stadia game streaming service, Linux seems to be good for low latency game streaming.
If we take a look at the download count of Sidequest, there are at least around 500 Linux Quest users. https://sidequestvr.com/#/download
I think Vulkan could be used for the encoding. The GUI would need to be rewritten in QT or something cross platform. But i think for the most Linux users a config-file would be enough.
Someone asked also on the original ALVR issue tracker for a Linux port and polygraphene gave an answer explaining what is needed to be done:
https://github.com/polygraphene/ALVR/issues/279

**Comment by JackD83** [comment]
ALVR is grown over the years and depends heavily on windows and windows only apis. I’m not saying that a Linux port would not be possible, but it would rather be a rewrite than a port. 
I have neither the time, the skill nor am I interested in doing this. But hey, its open source, everyone is invited to participate!

**Comment by poVoq** [comment]
Yeah that is understandable, but at least the Oculus Quest side of this project could maybe be used in common, right?

**Comment by poVoq** [comment]
Ahh and there was this project that might be worth a look:
https://github.com/MyrikLD/LinusTrinus
