### ISSUE TITLE
90Hz on Quest 2

### ISSUE THREAD

**Issue by ersan** [JackD83/ALVR#337]
Would like to see 90Hz support on Quest 2 - any time I change refreshRate to 90 it goes back to 72 on the next connection so I assume it is unsupported.

It seems to work fine in Virtual Desktop, for what it's worth.

**Comment by zarik5** [comment]
We don't have time to work around that, but it should work once 90Hz is officially supported.

**Comment by lyndonguitar** [comment]
> We don't have time to work around that, but it should work once 90Hz is officially supported.

i dont quite understand, my quest 2 is coming over the weekend and was wondering what to use in order to play at 90hz.

 What do you mean once 90hz is officially supported? u mean once oculus supports 90hz, ALVR will naturally work without further updates?  I've read about forcing 90hz support too in experimental settings, that wont work with ALVR? 

thanks

**Comment by zarik5** [comment]
@lyndonguitar ALVR queries the maximum supported framerate using the Oculus API. Until a firmware update from Oculus, the API will return always 72Hz at max. The reason you cannot force 90Hz using the ADB command is because ALVR sends the queried framerate value to the PC, so in the ends the framerate is dictated by the driver.

**Comment by lyndonguitar** [comment]
> @lyndonguitar ALVR queries the maximum supported framerate using the Oculus API. Until a firmware update from Oculus, the API will return always 72Hz at max. The reason you cannot force 90Hz using the ADB command is because ALVR sends the queried framerate value to the PC, so in the ends the framerate is dictated by the driver.

I see, thanks for clearing that up! If i understand correctly, VD and other 90hz games atm,  the app itself are updated on due to lack firmqare updates yet from oculus. I hope we get an update from oculus soon.

**Comment by xypherorion** [comment]
Tested again after the Oculus version 23 release. Still not getting 90hz as reported by SteamVR's in-headset monitor.
APK Needs an update:

https://developer.oculus.com/blog/-oculus-quest-v23-how-to-update-your-app-for-90hz/?locale=en_US

**Comment by JackD83** [comment]
The necessary changes are already made and will be available with the next release

**Comment by maxer456** [comment]
80 and 90 Hz refresh rate options are available as of ALVR v13.0.0.
