### ISSUE TITLE
will u be trying to take advantage of the oculus link software later this year

### ISSUE THREAD

**Issue by jakefever191** [JackD83/ALVR#47]
because of oculus making the oculus link that comes out in November will be able to take advantage of the oculus link software and improve alvr ? also will you keep working on alvr

**Comment by JackD83** [comment]
Currently, I have no idea if we could tap into the link software from oculus to improve ALVR. They only announced the tethered solution with the cable, so no wireless streaming. ALVR still has its usage.

Some of the optimizations they talked about at OC6 to make the streaming work are already implemented in ALVR. The distorting of the image to reduce the video resolution is exactly how our FFR works. 

Only time will tell if there will be a wireless solution from oculus. Rumor has it, that John Carmack is very interested in this topic. That's probably why they make the 6 month old Rift S obsolete over night.

**Comment by Sztrovacsek81** [comment]
Beside FFR there is one more important technical trick in Carmack's solution: not sending the whole frame, but slicing it to parts.
You can see this here around 4:40
https://www.youtube.com/watch?v=qcvGYD5sb-I

**Comment by JackD83** [comment]
Carmack had some more details in his own talk. He was able to remove some layers you normally have to talk to the video processor. I guess this is used to do the rendering of the slices on the quest. 
Encoding the slices should be possible in ALVR, but as far as I know, the android decoder takes a full frame to decode and present it. I'm no expert on this and if someone has some insights and expertise in this, don't be shy :)

**Comment by LibreGit** [comment]
Sadly I find the code related to frame decoding and rendering not easy to read. But since v7 it seems that you do some work on the Client between decoding the frame and rendering it.

Correct me if I'm wrong, but in v7 with the sliced ffr the received encoded frames are actually rescaled on the client after being decoded, and before being rendered.

So would it be possible to do something like :
On the server side :
- apply the sliced ffr
- split the resulting frame in 3 (or more) parts
- encode each part and send them separately

On the client side :
- receive first part, decode and store it
- receive second part, decode and store it
- receive third part, decode and store it
- reconstruct the frame from the 3 parts
- apply reverse sliced ffr to rescale the frame 
- render the resulting frame

**Comment by MPfaffe** [comment]
It seems something similiar has already been realized in another project:
[Tiled streaming](https://github.com/gpac/gpac/wiki/Tiled-Streaming) 

Some more Information/analyses:
[Multi Tile Streaming](https://www.google.com/url?sa=t&source=web&rct=j&url=https://hpcvis.org/publications/Streaming-EGPGV2018.pdf&ved=2ahUKEwi57LuJuvTlAhXDwsQBHRDEAuUQFjADegQIAxAB&usg=AOvVaw3DZ6GVVHJC1StsO4dfrpEd&cshid=1574103959450) 

In my Opinion this could reduce the latency (encode-transfer-decode) nearby to the transfer latency only...

**Comment by JackD83** [comment]
Its not a matter on how to do it. The concept is quite clear. The question is who and when.
Implementing this is a huge task and takes a lot of time I currently don't have.
