### ISSUE TITLE
after 20 mins alvr simple stops working.

### ISSUE THREAD

**Issue by BrotherO4** [JackD83/ALVR#54]
after 20 mins it seems like it stops streaming all together.
so there is a still image of what i last saw and blackness when i look away from that image. anyone knows why?

**Comment by FingrMastr** [comment]
It’s a known problem, I also have this issue. It randomly occurs. Also, there is also notable performance degradation in this time frame.

I started studying this problem last month. Since this is a very difficult bug to trace and resolve, I’m doing my best trying to optimize the quest clients app hoping to make the bug disappear, but still not sure it’s depending on it, or on server.

It occurs ALWAYS with Elite Deangerous, and with other games is mitigated, but it’s there.

For me, however, when the freeze occurs the Quest become completely unresponsive, even the right menu button is not pausing the app. Only if I close SteamVR (stopping streaming) it recovers. It seems to me that clearly the Client has some thread/concurrency problems. Trying to find cause for this.

**Comment by JackD83** [comment]
Please continue the discussion in #70
