### ISSUE TITLE
5ghz router

### ISSUE THREAD

**Issue by beyhes** [JackD83/ALVR#56]
Hi,
Do we need any specific feature when we buy router or any 5ghz router is compatible ?
Thanks :)

**Comment by KitsuneShan** [comment]
> Hi,
> Do we need any specific feature when we buy router or any 5ghz router is compatible ?
> Thanks :)

It really depends on each router and brand. Not all 5GHz routers are capable of delivering the same speed. While you don't need a 400$ router, it's advise to get at least a good one. I myself use an Asus one capable of delivering more than 1Gbps. You don't need such speed but if you will have attached other devices to the same WiFi signal, it's better to get one capable of handling one everything. The router also need ot be set to 40mhz as it seems to not work correctly under 80mhz. I didn't test myself this, mine was set on auto and was working, then I set it to 40 manually just in case so it kept working fine but I assume that under 20mhz and 80mhz may be some issues.

I personally would recommend doing one thing tho. What I did is, I already had a 5GHz router from my Internet provider since nowday all routers includes 5GHz WiFi. Under this one I had several other devices connected and it was working fine but I could get severe video artifacts from time to time. This one router it's good and capable of reaching high speed but I guess we can't help when you have a lot of devices. Fortunately I also had an Asus router that I don't use since it was meant to work with ADSL and since I have fiber I just kept the one from my Internet provider (it was working fine and pretty much offers the same as the Asus one so...). I used the Asus one as Access Point configuring it properly and connected it to the main router with a LAN ethernet cable. I then had two routers on the same network so I could enable two separated 5GHz signals. The Asus one it's solely for Quest with no encryption but using mac filter pointing to Quest so no other devices can use such signal. I made sure that it's also set at 40mhz and that the channel it's far enough from the main router channel so they don't overlap. With this setup, ALVR never had a single disconnection or video artifact ever streaming at 90Mbps 100% resolution with minimal latency (I use it for VRChat so the mimal latency isn't a big deal. It canbe reduced to almost none if I use FFR tho).

So that's it. If you have two routers or the possibility of having two, leave one solely for Quest, the setup it's easy and it will still remain on the same network so you can share files or use sidequest just fine. If you can only afford one router, leave the 5GHz one for Quest and the 2.4GHz for everything else or you can try using all on 5GHz as well, it may work if there isnt much heavy traffic and interferences. I am not an expert on this but I will assume that all 5GHz routers offers you the 40mhz band which is basically what you need (I have never seen a 5GHz router without 20, 40 and 80mhz bands to choose from).

As a reference point tho, you can check on the nvidia website about routers compatible with nvidia shield streaming. Those routers are the ones that can grant you enough speed for streaming with very little latency and it was on there where I found my Asus router since I got it years ago for my nvidia tablet. All the routers there will work with ALVR just fine so it's a good starting point if you want a list of good routers that surely will work. And not all of them are so expensive at all :) .

**Comment by beyhes** [comment]
Wow ! Thank you for very good and detailed explanation... You almost said preety much everything who may suffer with this issue like me.. I have ordered https://www.amazon.com/TP-LINK-Archer-VR600-Wireless-Support/dp/B06XW26XZ3  this one and just crossed fingers :) what do you think about it ?

**Comment by beyhes** [comment]
by the way sorry for my late reply.. cos after 3 days I asked my question no body answered.. so I just gave up checking :)

**Comment by KitsuneShan** [comment]
Looks like a pretty badass router. You should be fine with it ☺.

**Comment by beyhes** [comment]
hahaha thanks !! @KitsuneShan

**Comment by orangpelupa** [comment]
For those that are looking for a dirt cheap 5GHz router,

Xiaomi mi router 3 (not 3g not 3a, just 3)works well. Even on different room. 

Its been discontinued tho. Replaced by mi router 4 gigabit edition. 

I don't know it's the same performance, better, or worse.
