### ISSUE TITLE
How do you setup ALVR on different network

### ISSUE THREAD

**Issue by compubrain3000** [JackD83/ALVR#59]
So I see that remote network support was added in v6, but how exactly do you set it up specifically on a cloud computer?

**Comment by DavisNT** [comment]
1. UDP ports 9943 and 9944 of ALVR server must be accessible from Oculus Quest device (i.e. firewall openings must be made to allow Oculus Quest to connect to ALVR server UDP ports 9943 and 9944). 
1. Oculus Quest must be connected to computer and command-line `adb shell am startservice -n "com.polygraphene.alvr/.ChangeSettings" --es "targetServers" "10.10.10.10"` must be run in Command Prompt to specify IP address of ALVR server (`10.10.10.10` must be substituted with IP address of ALVR server; the long line is a single command line).
1. Next time when ALVR client will be started it should try to connect to the specified ALVR server. ALVR server should display the client in _Server_ tab (the same way local-network clients are displayed).

It is also suggested to use v7 as it has some bugs fixed.

**Comment by compubrain3000** [comment]
Sorry if I sound dumb but how do I know the IP address of the ALVR server? Does it need to have be a static IP?

**Comment by DavisNT** [comment]
@compubrain3000 The ALVR server IP address needs to be static (otherwise it would need to be changed in ALVR client every time it changes). 

A good starting point should be documentation of your cloud provider on how to make TCP/UDP ports of cloud computers/servers available from the internet. 
You can restrict access to ALVR server (UDP ports 9943 and 9944) by making them available only from your home IP address (public IP address of your home internet connection) using Windows Firewall (on the could server).

**Comment by compubrain3000** [comment]
Thanks for the help.

**Comment by DavisNT** [comment]
When writing "otherwise random people could gain access to your cloud server" I had forgotten that _Connect_ button needs to be pressed in ALVR server before new client's session start. 
Nevertheless IP restrictions should be implemented (as there might be ways how to start a session without _Connect_ being pressed in ALVR server).

**Comment by JackD83** [comment]
@DavisNT can you write a wiki page?

**Comment by DavisNT** [comment]
@JackD83 Wiki page created: https://github.com/JackD83/ALVR/wiki/ALVR-client-and-server-on-separate-networks
