### ISSUE TITLE
Plan for the future of ALVR

### ISSUE THREAD

**Issue by Ekristoffe** [JackD83/ALVR#76]
Hello guys,
First this is nor an issue but more a request.
I use the polygraphene/ALVR on my Oculus GO
I see you have done a lot of work on this fork for the Oculus Quest.
Do you have any plan in the future to also enable the Oculus GO ?
Is there a possibility for polygraphene to include the improvement you have done without becoming crasy ?
Thanks for all and keep up the good work.

**Comment by kikoano** [comment]
It works for GO up to experimental 2. Then for some random reason they remove the GO controller support. The streaming is best with experimental 7 and works on GO but not the GO controller. It is possible to merge the old removed GO code to experimental 7 and make it fully work but I dont have time for that right now. I hope someone makes this.

**Comment by JackD83** [comment]
I removed the old controller code because it was very hard to read and added extra latency to the tracking of the quest controllers using FreePie as an extra layer. Support for all other headsets got removed for the same reason.
You are welcome to merge all the changes of the rendering back into the main ALVR, but this fork will focus on the Quest.
